### ISSUE TITLE
Unhandled events

### ISSUE THREAD

**Issue by janispritzkau** [atom/event-kit#48]
Could we return a boolean value whether the event was handled or not in the `emit` method.
It could be useful to know if a error event was handled.

**Comment by rsese** [comment]
Thanks for the suggestion @janispritzkau - can you explain in more detail how this would be useful for Atom?

**Comment by janispritzkau** [comment]
Hmm, I haven't thought of that. I just asked because I use it in some of my personal projects and it's also used by many non-Atom related packages on npm.

I think I wanted to do something similar to how Node's EventEmitter handles errors.
Although I think this addition is not needed or useful in most projects.

**Comment by rsese** [comment]
Ahh ok, thanks for clarifying :+1:  We're not currently in a place to take on changes for use cases outside of Atom and maintain them moving forward unfortunately.  For now, we're recommending that people fork the repository if you have needs outside of Atom.

Since this isn't something the team will work on, I'm going to close the issue but thank you again for your interest.
